In [4]:
import pandas as pd
import bokeh

In [5]:
kyoto = pd.read_csv("site_restaurant_join.csv")

In [6]:
print(kyoto)

      r0001  s1  2.037775893  669  97.3339141         一蘭拉麵  35.0058787  \
0     r0001  s2     2.023311  358   90.341827         一蘭拉麵  35.0058787
1     r0001  s3     4.376297  517   93.500844         一蘭拉麵  35.0058787
2     r0001  s4    13.429932   58   63.944158         一蘭拉麵  35.0058787
3     r0001  s5     2.234828   43   78.766910         一蘭拉麵  35.0058787
4     r0001  s6     2.187607  104   79.383957         一蘭拉麵  35.0058787
5     r0001  s7     5.129946   43   72.081132         一蘭拉麵  35.0058787
6     r0001  s8     1.971776  132   58.970203         一蘭拉麵  35.0058787
7     r0001  s9     8.330669  373   89.341354         一蘭拉麵  35.0058787
8     r0002  s1     3.328348  555   87.125239   抹茶.甜點 中村藤吉  34.9853943
9     r0002  s2     1.256989  414   98.201541   抹茶.甜點 中村藤吉  34.9853943
10    r0002  s3     2.551602  498   94.373140   抹茶.甜點 中村藤吉  34.9853943
11    r0002  s4    11.577387   83   81.900563   抹茶.甜點 中村藤吉  34.9853943
12    r0002  s5     4.453591   68   94.319018   抹茶.甜點 中村藤吉  34.9853943
13    r0002  s6     0.256102  160   99.635206   抹茶.甜點 中村藤吉  34.9853943
14    r0002  s7     6.543913   76   92.080452   抹茶.甜點 中村藤吉  34.9853943
15    r0002  s8     2.659480  565   96.343186   抹茶.甜點 中村藤吉  34.9853943
16    r0002  s9     8.055617  375   89.951131   抹茶.甜點 中村藤吉  34.9853943
17    r0003  s1     3.249320  555   87.228634    抹茶甜點 中村藤吉  34.9861414
18    r0003  s2     1.239464  414   98.226615    抹茶甜點 中村藤吉  34.9861414
19    r0003  s3     2.617889  498   94.274698    抹茶甜點 中村藤吉  34.9861414
20    r0003  s4    11.652991   83   81.782368    抹茶甜點 中村藤吉  34.9861414
21    r0003  s5     4.370813   68   94.424610    抹茶甜點 中村藤吉  34.9861414
22    r0003  s6     0.183663  160   99.738389    抹茶甜點 中村藤吉  34.9861414
23    r0003  s7     6.468974   76   92.171145    抹茶甜點 中村藤吉  34.9861414
24    r0003  s8     2.626034  565   96.389175    抹茶甜點 中村藤吉  34.9861414
25    r0003  s9     8.024528  375   89.989913    抹茶甜點 中村藤吉  34.9861414
26    r0004  s1    14.682936  555   72.269676       中村藤吉本店   34.889426
27    r0004  s2    11.261750  414   83.887053       中村藤吉本店   34.889426
28    r0004  s3     8.931952  498   84.897802       中村藤吉本店   34.889426
29    r0004  s4     0.544586   83   99.148625       中村藤吉本店   34.889426
...     ...  ..          ...  ...         ...          ...         ...
2858  r0318  s7     5.168362    0   43.745167          Aow  35.0435944
2859  r0318  s8     5.407439    0   42.564714          Aow  35.0435944
2860  r0318  s9    10.396596    0   37.030909          Aow  35.0435944
2861  r0319  s1     2.434637    0   46.814689  CacaoMarket  35.0051258
2862  r0319  s2     1.914066    0   47.261416  CacaoMarket  35.0051258
2863  r0319  s3     4.255502    0   43.680234  CacaoMarket  35.0051258
2864  r0319  s4    13.246649    0   29.290933  CacaoMarket  35.0051258
2865  r0319  s5     2.441391    0   46.885772  CacaoMarket  35.0051258
2866  r0319  s6     2.289352    0   46.739030  CacaoMarket  35.0051258
2867  r0319  s7     5.471424    0   43.378396  CacaoMarket  35.0051258
2868  r0319  s8     1.616316    0   47.777547  CacaoMarket  35.0051258
2869  r0319  s9     8.737989    0   39.099916  CacaoMarket  35.0051258
2870  r0320  s1     6.811371    0   41.088470    Nagashima  34.9946724
2871  r0320  s2     4.377836    0   43.736334    Nagashima  34.9946724
2872  r0320  s3     5.083440    0   42.450679    Nagashima  34.9946724
2873  r0320  s4    11.736234    0   31.652231    Nagashima  34.9946724
2874  r0320  s5     6.207544    0   42.081684    Nagashima  34.9946724
2875  r0320  s6     5.486641    0   42.184788    Nagashima  34.9946724
2876  r0320  s7     9.564634    0   38.424728    Nagashima  34.9946724
2877  r0320  s8     3.095180    0   45.744095    Nagashima  34.9946724
2878  r0320  s9    13.103539    0   33.654169    Nagashima  34.9946724
2879  r0321  s1     2.066811    1   47.370665      Satsuki  35.0127658
2880  r0321  s2     2.761624    0   46.048757      Satsuki  35.0127658
2881  r0321  s3     5.110860    0   42.409959      Satsuki  35.0127658
2882  r0321  s4    14.106550    0   27.946612      Satsuki  35.0127658
2883  r0321  s5     1.610779    0   47.945298      Satsuki  35.0127658
2884  r0321  s6     2.989206    0   45.742153      Satsuki  35.0127658
2885  r0321  s7     4.798055    0   44.193318      Satsuki  35.0127658
2886  r0321  s8     2.375052    0   46.734278      Satsuki  35.0127658
2887  r0321  s9     8.522920    0   39.368200      Satsuki  35.0127658

      135.7681023     二條城  35.0142299  135.748218
0     135.7681023   三十三間堂   34.987884  135.771713
1     135.7681023    千本鳥居   34.966813  135.774749
2     135.7681023  平等院鳳凰堂   34.889291  135.807678
3     135.7681023    京都御所   35.025413  135.762125
4     135.7681023     京都塔   34.987477  135.759493
5     135.7681023     金閣寺   35.039355  135.729326
6     135.7681023     清水寺   34.994856  135.785046
7     135.7681023     渡月橋   35.014500  135.677438
8      135.758282     二條城   35.014230  135.748218
9      135.758282   三十三間堂   34.987884  135.771713
10     135.758282    千本鳥居   34.966813  135.774749
11     135.758282  平等院鳳凰堂   34.889291  135.807678
12     135.758282    京都御所   35.025413  135.762125
13     135.758282     京都塔   34.987477  135.759493
14     135.758282     金閣寺   35.039355  135.729326
15     135.758282     清水寺   34.994856  135.785046
16     135.758282     渡月橋   35.014500  135.677438
17    135.7583035     二條城   35.014230  135.748218
18    135.7583035   三十三間堂   34.987884  135.771713
19    135.7583035    千本鳥居   34.966813  135.774749
20    135.7583035  平等院鳳凰堂   34.889291  135.807678
21    135.7583035    京都御所   35.025413  135.762125
22    135.7583035     京都塔   34.987477  135.759493
23    135.7583035     金閣寺   35.039355  135.729326
24    135.7583035     清水寺   34.994856  135.785046
25    135.7583035     渡月橋   35.014500  135.677438
26     135.801723     二條城   35.014230  135.748218
27     135.801723   三十三間堂   34.987884  135.771713
28     135.801723    千本鳥居   34.966813  135.774749
29     135.801723  平等院鳳凰堂   34.889291  135.807678
...           ...     ...         ...         ...
2858   135.785736     金閣寺   35.039355  135.729326
2859   135.785736     清水寺   34.994856  135.785046
2860   135.785736     渡月橋   35.014500  135.677438
2861  135.7724874     二條城   35.014230  135.748218
2862  135.7724874   三十三間堂   34.987884  135.771713
2863  135.7724874    千本鳥居   34.966813  135.774749
2864  135.7724874  平等院鳳凰堂   34.889291  135.807678
2865  135.7724874    京都御所   35.025413  135.762125
2866  135.7724874     京都塔   34.987477  135.759493
2867  135.7724874     金閣寺   35.039355  135.729326
2868  135.7724874     清水寺   34.994856  135.785046
2869  135.7724874     渡月橋   35.014500  135.677438
2870   135.818949     二條城   35.014230  135.748218
2871   135.818949   三十三間堂   34.987884  135.771713
2872   135.818949    千本鳥居   34.966813  135.774749
2873   135.818949  平等院鳳凰堂   34.889291  135.807678
2874   135.818949    京都御所   35.025413  135.762125
2875   135.818949     京都塔   34.987477  135.759493
2876   135.818949     金閣寺   35.039355  135.729326
2877   135.818949     清水寺   34.994856  135.785046
2878   135.818949     渡月橋   35.014500  135.677438
2879  135.7707922     二條城   35.014230  135.748218
2880  135.7707922   三十三間堂   34.987884  135.771713
2881  135.7707922    千本鳥居   34.966813  135.774749
2882  135.7707922  平等院鳳凰堂   34.889291  135.807678
2883  135.7707922    京都御所   35.025413  135.762125
2884  135.7707922     京都塔   34.987477  135.759493
2885  135.7707922     金閣寺   35.039355  135.729326
2886  135.7707922     清水寺   34.994856  135.785046
2887  135.7707922     渡月橋   35.014500  135.677438

[2888 rows x 11 columns]

In [7]:
print(kyoto.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2888 entries, 0 to 2887
Data columns (total 11 columns):
r0001          2888 non-null object
s1             2888 non-null object
2.037775893    2888 non-null float64
669            2888 non-null int64
97.3339141     2888 non-null float64
一蘭拉麵           2888 non-null object
35.0058787     2888 non-null object
135.7681023    2888 non-null object
二條城            2888 non-null object
35.0142299     2888 non-null float64
135.748218     2888 non-null float64
dtypes: float64(4), int64(1), object(6)
memory usage: 248.3+ KB
None

In [9]:
type(kyoto)

pandas.core.frame.DataFrame

In [20]:
kyoto.head()

,r0001,s1,2.037775893,669,97.3339141,一蘭拉麵,35.0058787,135.7681023,二條城,35.0142299,135.748218
0,r0001,s2,2.023311,358,90.341827,一蘭拉麵,35.0058787,135.7681023,三十三間堂,34.987884,135.771713
1,r0001,s3,4.376297,517,93.500844,一蘭拉麵,35.0058787,135.7681023,千本鳥居,34.966813,135.774749
2,r0001,s4,13.429932,58,63.944158,一蘭拉麵,35.0058787,135.7681023,平等院鳳凰堂,34.889291,135.807678
3,r0001,s5,2.234828,43,78.766910,一蘭拉麵,35.0058787,135.7681023,京都御所,35.025413,135.762125
4,r0001,s6,2.187607,104,79.383957,一蘭拉麵,35.0058787,135.7681023,京都塔,34.987477,135.759493